In [2]:
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [3]:
df = pd.DataFrame({'A':1,
                   'B':1,
                   'C':["Steph","Dylan","Kate","Fred","Mike"],
                   'D':[3.14,4,5,6,7]})
df

   A  B      C     D
0  1  1  Steph  3.14
1  1  1  Dylan  4.00
2  1  1   Kate  5.00
3  1  1   Fred  6.00
4  1  1   Mike  7.00

In [4]:
df.dtypes

A      int64
B      int64
C     object
D    float64
dtype: object

In [5]:
df.iloc[0:2,0:3]

   A  B      C
0  1  1  Steph
1  1  1  Dylan

In [6]:
df.loc[[0,3],["A","C"]]

   A      C
0  1  Steph
3  1   Fred

In [7]:
df["A"]

0    1
1    1
2    1
3    1
4    1
Name: A, dtype: int64

In [8]:
df["A"].shape

(5,)

In [9]:
df[["A","B"]].shape

(5, 2)

In [10]:
df[["A",'B']]

   A  B
0  1  1
1  1  1
2  1  1
3  1  1
4  1  1

In [11]:
my_bool = [True, False, True, False, True]
df.loc[my_bool]

   A  B      C     D
0  1  1  Steph  3.14
2  1  1   Kate  5.00
4  1  1   Mike  7.00

In [ ]:
df_rpkms = pd.read_csv("RNA.gz", compression="gzip",skiprows=2,sep="\t")

In [13]:
df_rpkms #this is the amount of expression for each gene (row) and sample (column)

,Name,Description,GTEX-N7MS-0007-SM-2D7W1,GTEX-N7MS-0011-R10A-SM-2HMJK,GTEX-N7MS-0011-R11A-SM-2HMJS,GTEX-N7MS-0011-R1a-SM-2HMJG,GTEX-N7MS-0011-R2a-SM-2HML6,GTEX-N7MS-0011-R3a-SM-33HC6,GTEX-N7MS-0011-R4a-SM-2HMKW,GTEX-N7MS-0011-R5a-SM-2HMK8,...,GTEX-X4LF-0526-SM-3NMB6,GTEX-X4LF-1726-SM-3NMBZ,GTEX-X4XX-0005-SM-3NMCS,GTEX-X4XX-0011-R1B-SM-3P622,GTEX-X4XX-0011-R2A-SM-3P623,GTEX-X4XX-0126-SM-3NMC2,GTEX-X4XX-0626-SM-3NMC1,GTEX-X4XX-1126-SM-3NMBY,GTEX-X4XX-2926-SM-3NMB1,GTEX-X4XX-3026-SM-3NMB2
0,ENSG00000223972.4,DDX11L1,0.000000,0.000000,0.000000,0.000000,0.000000,0.029181,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.050261,0.000000
1,ENSG00000227232.3,WASH7P,2.917592,1.958602,5.841671,1.728239,2.315600,3.742634,2.269886,2.442356,...,9.417033,7.007399,6.276984,3.710413,5.769073,12.540883,4.696292,4.555761,9.459983,5.700174
2,ENSG00000243485.1,MIR1302-11,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.102921,0.000000,0.000000,0.000000,0.000000,0.000000
3,ENSG00000237613.2,FAM138A,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,ENSG00000240361.1,OR4G11P,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.015078,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52571,ENSG00000198786.2,MT-ND5,627.419189,3967.486572,1014.433228,4683.750000,2813.970947,2435.256104,3997.514893,5427.200684,...,3997.743164,1589.340210,277.970520,7192.353516,1723.450684,2418.593018,3559.731689,2795.689209,1894.077515,3302.491699
52572,ENSG00000198695.2,MT-ND6,553.020569,2737.471680,787.444824,3694.725342,1631.243652,2049.827148,2676.096191,3723.490234,...,6915.279297,1867.175537,400.203766,8612.575195,1159.216675,4115.834473,5160.529297,2533.044434,1654.201904,3118.078125
52573,ENSG00000210194.1,J01415.21,0.434417,0.000000,0.243951,0.847667,0.000000,0.357784,1.051482,0.811884,...,2.372880,0.214025,0.000000,0.974938,0.199876,0.621196,1.584828,0.217481,0.410828,0.000000
52574,ENSG00000198727.2,MT-CYB,2022.417969,20763.693359,7525.217285,24014.476562,13874.849609,12816.257812,18059.113281,26712.630859,...,7216.080078,9511.128906,1375.219727,24179.337891,3829.971191,10955.970703,10365.626953,20897.306641,7734.621094,12888.306641
52575,ENSG00000210195.2,J01415.22,0.000000,0.476469,0.255039,0.590798,0.371512,0.000000,0.000000,0.424394,...,0.000000,0.000000,0.000000,0.203851,0.208961,0.000000,0.828433,0.000000,0.000000,0.418731

In [14]:
df_rpkms.median(axis = 1) #median of gene expression for each gene for all samples.

0           0.000000
1           5.917334
2           0.000000
3           0.000000
4           0.000000
            ...
52571    2376.176025
52572    2423.041016
52573       0.342601
52574    8809.516602
52575       0.000000
Length: 52576, dtype: float64

In [15]:
roi = df_rpkms.median(axis=1) > 0 #will show all expression of genes that express more than 0
#you don't have to use an if statement because of pandas
roi

0        False
1         True
2        False
3        False
4        False
         ...
52571     True
52572     True
52573     True
52574     True
52575    False
Length: 52576, dtype: bool

In [16]:
df_rpkms = df_rpkms.loc[roi, :]
df_rpkms

,Name,Description,GTEX-N7MS-0007-SM-2D7W1,GTEX-N7MS-0011-R10A-SM-2HMJK,GTEX-N7MS-0011-R11A-SM-2HMJS,GTEX-N7MS-0011-R1a-SM-2HMJG,GTEX-N7MS-0011-R2a-SM-2HML6,GTEX-N7MS-0011-R3a-SM-33HC6,GTEX-N7MS-0011-R4a-SM-2HMKW,GTEX-N7MS-0011-R5a-SM-2HMK8,...,GTEX-X4LF-0526-SM-3NMB6,GTEX-X4LF-1726-SM-3NMBZ,GTEX-X4XX-0005-SM-3NMCS,GTEX-X4XX-0011-R1B-SM-3P622,GTEX-X4XX-0011-R2A-SM-3P623,GTEX-X4XX-0126-SM-3NMC2,GTEX-X4XX-0626-SM-3NMC1,GTEX-X4XX-1126-SM-3NMBY,GTEX-X4XX-2926-SM-3NMB1,GTEX-X4XX-3026-SM-3NMB2
1,ENSG00000227232.3,WASH7P,2.917592,1.958602,5.841671,1.728239,2.315600,3.742634,2.269886,2.442356,...,9.417033,7.007399,6.276984,3.710413,5.769073,12.540883,4.696292,4.555761,9.459983,5.700174
6,ENSG00000238009.2,RP11-34P13.7,0.177576,0.204927,0.289186,0.248324,0.268730,0.168188,0.408321,0.219865,...,0.229263,0.218716,0.658286,0.314833,0.514728,0.389351,0.255082,0.248918,0.487006,0.290606
7,ENSG00000239945.1,RP11-34P13.8,0.272705,0.202653,0.510465,0.280842,0.316025,0.162210,0.715072,0.254829,...,0.270831,0.134354,0.687998,0.479412,0.533255,0.357458,0.248718,0.273047,0.591012,0.261905
8,ENSG00000237683.3,RP11-34P13.11,88.187675,1.009232,1.577608,0.575865,0.981906,0.532865,1.030279,0.767670,...,10.860014,2.222919,128.481339,2.991933,1.625518,10.951993,0.531858,4.747769,3.747678,2.664726
9,ENSG00000239906.1,RP11-34P13.14,21.158670,0.097359,0.208453,0.000000,0.227738,0.152861,0.000000,0.130077,...,1.013800,0.457205,11.639369,0.208268,0.170792,0.928909,0.126958,0.371670,0.526572,0.171122
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52566,ENSG00000198840.2,MT-ND3,546.563416,9898.380859,4572.871582,10415.388672,7144.897461,6341.940430,8621.208984,10017.948242,...,3578.243652,5226.624023,870.697571,13152.982422,3865.071777,4782.514160,3418.035400,16177.149414,4064.408936,6445.033691
52571,ENSG00000198786.2,MT-ND5,627.419189,3967.486572,1014.433228,4683.750000,2813.970947,2435.256104,3997.514893,5427.200684,...,3997.743164,1589.340210,277.970520,7192.353516,1723.450684,2418.593018,3559.731689,2795.689209,1894.077515,3302.491699
52572,ENSG00000198695.2,MT-ND6,553.020569,2737.471680,787.444824,3694.725342,1631.243652,2049.827148,2676.096191,3723.490234,...,6915.279297,1867.175537,400.203766,8612.575195,1159.216675,4115.834473,5160.529297,2533.044434,1654.201904,3118.078125
52573,ENSG00000210194.1,J01415.21,0.434417,0.000000,0.243951,0.847667,0.000000,0.357784,1.051482,0.811884,...,2.372880,0.214025,0.000000,0.974938,0.199876,0.621196,1.584828,0.217481,0.410828,0.000000
52574,ENSG00000198727.2,MT-CYB,2022.417969,20763.693359,7525.217285,24014.476562,13874.849609,12816.257812,18059.113281,26712.630859,...,7216.080078,9511.128906,1375.219727,24179.337891,3829.971191,10955.970703,10365.626953,20897.306641,7734.621094,12888.306641

In [17]:
df_metadata = pd.read_csv("GTEx.txt", sep="/t")
df_metadata

/Users/cmdb/miniconda3/envs/cmdb/lib/python3.6/site-packages/ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.

ParserError: Expected 1 fields in line 707, saw 2. Error could possibly be due to quotes being ignored when a multi-char delimiter is used.

In [ ]:
df_metadata =

In [ ]:
pca_input = df_rpkms.iloc[:,2:]
pca_input

In [ ]:
pca_input = pca_input.T #Will transport the axis
pca_input

In [ ]:
pca_input.mean(axis=0) #median

In [ ]:
pca_input_standardized = StandardScaler().fit_transform #Normalize the data, will make gene expression 0

In [ ]:
pca_input_standardized.var(axis=0)

In [ ]:
pca=PCA(n_components = 10) #How many variables you want to study
pca_output = pca.fit_transform()#This is how you run PCA
pca_output

In [ ]:
pca_output.shape #Size of data

In [ ]:
#Store in a pandas data frame
pca_output_df = pd.DataFrame(data = pca_output, 
                            columns = ['PCA1','PCA2','PCA3','PCA4'.'PCA5','PCA6','PCA7','PCA8','PCA9','PCA10'])

In [ ]:
#plot data
fig, ax = plt.subplots()
ax.scatter(x = pca_output_df['PCA1'], y=pca_output_df['PCA2'])

In [ ]:
#How to get row names
pca_output_df['SAMPID'] = pca_input.index
pca_output_df

In [ ]:
df_metabata #table with info on sample and type of tissue

In [30]:
pca_outputpd_df = pd.merge(pca_output_df,df_metadata, on='SAMPID')

NameError: name 'pca_outputpd' is not defined

In [ ]:
#plot data
fig, ax = plt.subplots()
tissues = pca_output_df.grouphy("SMTS") #grouphy makes groups depending on tissue type
    ax.scatter(x=group['PC1'], y=group['PCA2'], label=name)


ax.scatter(x = pca_output_df['PCA1'], y=pca_output_df['PCA2'])

plt.legend(bbox_to_anchor = (1.7,1), loc = 'upper right', ncol=2)